from holiman/hera

USER root

RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - && \
    sudo apt install -y nodejs

USER builder

RUN echo "hello world"

RUN rm -rf evm2wasm && \
          git clone --recursive https://github.com/ewasm/evm2wasm --single-branch -b trace-fix && \
          cd evm2wasm && \
          npm install && \
          cd tools/wabt && \
          cmake -DBUILD_TESTS=OFF && \
          make -j8


ENV PATH="${PATH}:/home/builder/evm2wasm/bin"
